version: '3.8'

services:
  db:
    image: toshiro_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toshiro_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - toshiro-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: toshiro_app
    networks:
      - toshiro-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - toshiro-network
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  toshiro-network:
